### ISSUE TITLE
[Issue 4a-01] Testing with DatabaseManager

### ISSUE THREAD

**Issue by GlassInterface** [CSC207-2022F-UofT/course-project-wanna-date#33]
Since DatabaseManager involves a static context, it is hard to test the Recommendation use case. How might the use of the Manager be changed so that testing is easier? Conference with Lovina and others.

**Comment by lovinalokeswara** [comment]
Hi Aarist, the DatabaseManager should have private constructor. This is because the DatabaseManager represents a Singleton Class. The database can be edited, but there can only be 1 DatabaseManager which refers to the same Database. To access the Database,
DatabaseManager databaseManager = DatabaseManager.getDatabaseManager();
UserDatabase database = databaseManager.getDatabase();

You are not allowed to write the code: new DatabaseManager();
But you're allowed to use any other functions defined in the DatabaseManager class that are public

Tell me if you encounter any problems
